### PR TITLE
decouple IBCAction from specific proto format

### PR DESCRIPTION
**Pull request by avahowell**
previously, the IBCAction type was an explicit protobuf `oneof` that enumerated all of the specific IBC action types (CreateClient, UpdateClient, etc), binding to their specific proto version and forcing us to vendor IBC protobufs. This PR changes the IBCAction type to contain a `raw_action`, which is an `Any`. This way, we can rely solely on the decoding logic in the `ibc-proto` crate, instead of *both* the crate and the vendored protos. Also, this makes updates to the IBC protos less painful, since we only need to update our node-side decoding logic and not all of our clients.

### CODE REVIEW

**Comment by hdevalence** [comment]
Looks like the `wkt-types` isn't working because it's deferring some codegen to build time, I guess it has to be bundled into the `tools/proto-compiler`?

**Comment by avahowell** [comment]
I think we need to check in the generated types for `Any` etc in the proto compiler

**Comment by avahowell** [comment]
Updated this by adding our own serde implementation instead of using `wkt-types`, rebased on to latest main, IBC test passing

**Comment by hdevalence** [comment]
This subsumes #1768 right?

**Review by hdevalence — APPROVED** [review]

**Comment by avahowell** [comment]
Yes

**Pull request merged**
