### PR TITLE
valetudo: edit genesis supply

### PR DESCRIPTION
**Pull request by hdevalence**

### CODE REVIEW

**Comment by zbuc** [comment]
We should integrate this into the `setup_validator.py` script, maybe it should accept a genesis JSON file via CLI flag?

**Comment by hdevalence** [comment]
Sure, alternatively it could just pull in a JSON file with the app data rather than the full genesis data, and stick it into the `app_state` field?

**Comment by zbuc** [comment]
That works too. Were these notes generated for the `penumbrav0t1kfsawc5le7y3ptzmr2vdrgd3nlldytzeyss5pfrwqsn3xact9yc2jh4f7zqvvyjqnlhsyv8auncs49thgxvf23cc00l0qpv9alghjxfdyzyjp2943mhjg0sxnd4nk5` address?

**Comment by kwf** [comment]
I like the approach of pulling in the JSON file with the app data, +1 to that.

**Comment by hdevalence** [comment]
The invocation I used was:
```
"(200000, penumbra,      penumbrav0t1na5duj20at9k3faq8cvqf3ykk0vkh326q2klp9phz5vp2ndy3mnqx9x28yzrdxyc0p9qv68j4zegs4augceu6nj9g9ylnmxu0eg7st3mshkhsqjy7248x2gszpsfj9)" \
"(2000,   pizza,         penumbrav0t1na5duj20at9k3faq8cvqf3ykk0vkh326q2klp9phz5vp2ndy3mnqx9x28yzrdxyc0p9qv68j4zegs4augceu6nj9g9ylnmxu0eg7st3mshkhsqjy7248x2gszpsfj9)" \
"(200,    tungsten_cube, penumbrav0t1na5duj20at9k3faq8cvqf3ykk0vkh326q2klp9phz5vp2ndy3mnqx9x28yzrdxyc0p9qv68j4zegs4augceu6nj9g9ylnmxu0eg7st3mshkhsqjy7248x2gszpsfj9)" \
"(400,    gm,            penumbrav0t1na5duj20at9k3faq8cvqf3ykk0vkh326q2klp9phz5vp2ndy3mnqx9x28yzrdxyc0p9qv68j4zegs4augceu6nj9g9ylnmxu0eg7st3mshkhsqjy7248x2gszpsfj9)" \
"(400,    gn,            penumbrav0t1na5duj20at9k3faq8cvqf3ykk0vkh326q2klp9phz5vp2ndy3mnqx9x28yzrdxyc0p9qv68j4zegs4augceu6nj9g9ylnmxu0eg7st3mshkhsqjy7248x2gszpsfj9)" \
"(200000, penumbra,      penumbrav0t14k6uhn8pnuvm869h3kgfywk03cn8nxv4fgu2ehdjdrgk2277lgsp7qrzduzyka2v3pfsy8py259ge9eq36nq8czsjgjsm5rv28s9mq54z3yw3veyz52lt0qsfp29w3)" \
"(2000,   pizza,         penumbrav0t14k6uhn8pnuvm869h3kgfywk03cn8nxv4fgu2ehdjdrgk2277lgsp7qrzduzyka2v3pfsy8py259ge9eq36nq8czsjgjsm5rv28s9mq54z3yw3veyz52lt0qsfp29w3)" \
"(200,    tungsten_cube, penumbrav0t14k6uhn8pnuvm869h3kgfywk03cn8nxv4fgu2ehdjdrgk2277lgsp7qrzduzyka2v3pfsy8py259ge9eq36nq8czsjgjsm5rv28s9mq54z3yw3veyz52lt0qsfp29w3)" \
"(400,    gm,            penumbrav0t14k6uhn8pnuvm869h3kgfywk03cn8nxv4fgu2ehdjdrgk2277lgsp7qrzduzyka2v3pfsy8py259ge9eq36nq8czsjgjsm5rv28s9mq54z3yw3veyz52lt0qsfp29w3)" \
"(400,    gn,            penumbrav0t14k6uhn8pnuvm869h3kgfywk03cn8nxv4fgu2ehdjdrgk2277lgsp7qrzduzyka2v3pfsy8py259ge9eq36nq8czsjgjsm5rv28s9mq54z3yw3veyz52lt0qsfp29w3)" \
"(200000, penumbra,      penumbrav0t1lvuh7w9judw4wgdjkqmt7jc9crtsssz9phz7e2cxcdeeqeulcz8pzegnkkc2hen8l9nslvqrp2x5vhuvxtd8vyt22lm7g566nveg2y4zzve2vk25jgs29pqtpmguef)" \
"(2000,   pizza,         penumbrav0t1lvuh7w9judw4wgdjkqmt7jc9crtsssz9phz7e2cxcdeeqeulcz8pzegnkkc2hen8l9nslvqrp2x5vhuvxtd8vyt22lm7g566nveg2y4zzve2vk25jgs29pqtpmguef)" \
"(200,    tungsten_cube, penumbrav0t1lvuh7w9judw4wgdjkqmt7jc9crtsssz9phz7e2cxcdeeqeulcz8pzegnkkc2hen8l9nslvqrp2x5vhuvxtd8vyt22lm7g566nveg2y4zzve2vk25jgs29pqtpmguef)" \
"(400,    gm,            penumbrav0t1lvuh7w9judw4wgdjkqmt7jc9crtsssz9phz7e2cxcdeeqeulcz8pzegnkkc2hen8l9nslvqrp2x5vhuvxtd8vyt22lm7g566nveg2y4zzve2vk25jgs29pqtpmguef)" \
"(400,    gn,            penumbrav0t1lvuh7w9judw4wgdjkqmt7jc9crtsssz9phz7e2cxcdeeqeulcz8pzegnkkc2hen8l9nslvqrp2x5vhuvxtd8vyt22lm7g566nveg2y4zzve2vk25jgs29pqtpmguef)" \
"(200000, penumbra,      penumbrav0t1hqllugj25ql7efk4pxmglj8ywax9n94p3vlh0kxwanyrepcnsvkurgmc3q3ejnjdtg2qq6xj8txcwdlvyspzwysyu33f9s5qzysc6sv4wyf4fj6drze9ltcfw6cpws)" \
"(2000,   pizza,         penumbrav0t1hqllugj25ql7efk4pxmglj8ywax9n94p3vlh0kxwanyrepcnsvkurgmc3q3ejnjdtg2qq6xj8txcwdlvyspzwysyu33f9s5qzysc6sv4wyf4fj6drze9ltcfw6cpws)" \
"(200,    tungsten_cube, penumbrav0t1hqllugj25ql7efk4pxmglj8ywax9n94p3vlh0kxwanyrepcnsvkurgmc3q3ejnjdtg2qq6xj8txcwdlvyspzwysyu33f9s5qzysc6sv4wyf4fj6drze9ltcfw6cpws)" \
"(400,    gm,            penumbrav0t1hqllugj25ql7efk4pxmglj8ywax9n94p3vlh0kxwanyrepcnsvkurgmc3q3ejnjdtg2qq6xj8txcwdlvyspzwysyu33f9s5qzysc6sv4wyf4fj6drze9ltcfw6cpws)" \
"(400,    gn,            penumbrav0t1hqllugj25ql7efk4pxmglj8ywax9n94p3vlh0kxwanyrepcnsvkurgmc3q3ejnjdtg2qq6xj8txcwdlvyspzwysyu33f9s5qzysc6sv4wyf4fj6drze9ltcfw6cpws)" \
"(200000, penumbra,      penumbrav0t1jwjg4yjw7mhcz73mu6yxr3wf6ez6r8pftpfxvr5f5datns4wcqpyl3ls8qw8jzdf4tuqgl46kwqean77lr9f2k599f09fjxv4qgyfczghwgzy05es0zke2cvgkwc45)" \
"(2000,   pizza,         penumbrav0t1jwjg4yjw7mhcz73mu6yxr3wf6ez6r8pftpfxvr5f5datns4wcqpyl3ls8qw8jzdf4tuqgl46kwqean77lr9f2k599f09fjxv4qgyfczghwgzy05es0zke2cvgkwc45)" \
"(200,    tungsten_cube, penumbrav0t1jwjg4yjw7mhcz73mu6yxr3wf6ez6r8pftpfxvr5f5datns4wcqpyl3ls8qw8jzdf4tuqgl46kwqean77lr9f2k599f09fjxv4qgyfczghwgzy05es0zke2cvgkwc45)" \
"(400,    gm,            penumbrav0t1jwjg4yjw7mhcz73mu6yxr3wf6ez6r8pftpfxvr5f5datns4wcqpyl3ls8qw8jzdf4tuqgl46kwqean77lr9f2k599f09fjxv4qgyfczghwgzy05es0zke2cvgkwc45)" \
"(400,    gn,            penumbrav0t1jwjg4yjw7mhcz73mu6yxr3wf6ez6r8pftpfxvr5f5datns4wcqpyl3ls8qw8jzdf4tuqgl46kwqean77lr9f2k599f09fjxv4qgyfczghwgzy05es0zke2cvgkwc45)" \
"(5000,   nala,          penumbrav0t14k6uhn8pnuvm869h3kgfywk03cn8nxv4fgu2ehdjdrgk2277lgsp7qrzduzyka2v3pfsy8py259ge9eq36nq8czsjgjsm5rv28s9mq54z3yw3veyz52lt0qsfp29w3)" \
```

**Review by zbuc — APPROVED** [review]

**Comment by zbuc** [comment]
Closing in favor of #217

**Pull request closed without merging**
