### PR TITLE
staking: remove `component::FP_SCALING_FACTOR` dup

### PR DESCRIPTION
**Pull request by erwanor**
This should fix the wasm build unless something else is wrong. The problem was that we defined the same constant (`FP_SCALING_FACTOR`) twice, once correctly at the crate-level, and another one in `penumbra_stake::component`. During development, the latter one was used and created a discreet dependency on the component module.

x-ref #3894

### CODE REVIEW

**Comment by hdevalence** [comment]
Before merging, can we

- [ ] Check that this works with the extension's wasm build (#3894) cc @turbocrime 
- [ ] Bump the workspace version so we can immediately do a new tag

**Comment by turbocrime** [comment]
made one minor change, building successfully with a dep on this branch, will PR in web repo in a sec

**Comment by turbocrime** [comment]
Screenshot 2024-02-26 at 12 15 57

**Comment by turbocrime** [comment]
Screenshot 2024-02-26 at 12 22 25
jk it works

**Comment by hdevalence** [comment]
@turbocrime oh great, is that screenshot also indicating that the updated proof params work with `testnet-preview`?

**Comment by turbocrime** [comment]
> @turbocrime oh great, is that screenshot also indicating that the updated proof params work with `testnet-preview`?

they work enough to make a send tx, yes

**Pull request merged**
