### PR TITLE
account_group_id -> wallet

### PR DESCRIPTION
**Pull request by grod220**
Closes #https://github.com/penumbra-zone/penumbra/issues/2997

### CODE REVIEW

**Comment by hdevalence** [comment]
One thing I don't think we settled on: up to this point, the "account group ID" has been a purely internal name, only used in internal code and datastructures. Adding a Bech32 prefix for it feels like making it in some sense user-facing (at least to a subset of users).

Did we want to align on terminology first? We'd talked about having a conceptual hierarchy of "wallet" / "account" / "address" for spend capability / logical account / payment capability that we currently call "account group" / "account" / "address". Should we commit to that?

**Comment by grod220** [comment]
@hdevalence I think that terminology makes sense! There also seemed to be consensus on the team meeting with it too. Changed all instances of account group id to wallet.

**Comment by hdevalence** [comment]
I hate to ask to redo everything, but I'm wondering if we could call it `WalletId` rather than `Wallet`. It seems kind of important to have the name clarify that it's just an identifier, it doesn't actually do anything itself -- if we call it "wallet", I think someone reading the code or API docs could easily get confused thinking that it was the thing that manages funds, rather than _just_ being an identifier.

**Comment by grod220** [comment]
I wasn't sure if this struct would be something later down the line we'd extend. I had a hunch about Id though. Wasn't terribly hard to add.

**Comment by grod220** [comment]
@hdevalence thanks for the re-review 🙏

**Pull request merged**
