### PR TITLE
feat(dev): add nix-based dev-env

### PR DESCRIPTION
**Pull request by conorsch**
## Describe your changes
Trying to make it easier to spin up a fullnode on localhost. The team has been focused on writing tooling, like pindexer, and the manual steps to munge CometBFT configs and setup a localhost postgres database are not awesome. In addition to pd/cometbft spin-up, the dev-env includes:

  * metrics
  * postgres
  * pindexer

Not yet including grpcui, because the latest published version doesn't support the new server reflection API. Will tack that on in a dedicated follow-up.

The dev-env is strongly opinionated and uses nix [0] to manage cross-platform, polyglot dependencies. There's other great work in our ecosystem, e.g. [1], and this early push tries to be consistent with that.

Updates the relevant first-run docs. Much more work should be done on the developer-focused content in the guide overall, including an overhaul of discussing RPC endpoints and web-relevant resources, but those changes can land in the future. This PR aims to establish a basis for a sane, supported dev-env, providing a pleasant first-run experience for newcomers (and existing devs too).

[0] https://nixos.org
[1] https://github.com/informalsystems/cosmos.nix

Here's an example of what the `just dev` command looks like:

process-compose-nix-dev-env-screenshot

## Issue ticket number and link
No issue, but this PR builds on the excellent foundation by @cratelyn in #3574. 

## Checklist before requesting a review

- [x] If this code contains consensus-breaking changes, I have added the "consensus-breaking" label. Otherwise, I declare my belief that there are not consensus-breaking changes, for the following reason:

  > No changes to application code: focuses on docs and scripts for dev/ci.
  
## Testing and review

In order to review these changes, one should check out this feature branch, build the dev docs in `docs/guide/`, and view them locally, then follow the instructions at http://127.0.0.1:3000/dev/dev-env.html. Pay attention to what's confusing, what's unpleasant, and write those thoughts down as part of the review.

Then proceed to http://127.0.0.1:3000/dev/devnet-quickstart.html and run `just dev` as recommended. Does anything break? Does it work as advertised? Is anything unclear? Try running `ctrl+c` to stop the setup, and then `just dev` to resume it. Does it come back up OK? Is that a sane behavior?

### CODE REVIEW

**Comment by zbuc** [comment]
Guide was easy to follow, but I got this error when trying to run `nix develop` on macOS:

```
nix develop
error (ignored): error: end of string reached
error:
       … while calling the 'derivationStrict' builtin
         at <nix/derivation-internal.nix>:9:12:
            8|
            9|   strict = derivationStrict drvAttrs;
             |            ^
           10|

       … while evaluating derivation 'nix-shell'
         whose name attribute is located at /nix/store/iqxdbcjlg9wx8gdc8bdhy9nsd5imcbjp-source/pkgs/stdenv/generic/make-derivation.nix:334:7

       … while evaluating attribute '__impureHostDeps' of derivation 'nix-shell'
         at /nix/store/iqxdbcjlg9wx8gdc8bdhy9nsd5imcbjp-source/pkgs/stdenv/generic/make-derivation.nix:449:7:
          448|       __propagatedSandboxProfile = unique (computedPropagatedSandboxProfile ++ [ propagatedSandboxProfile ]);
          449|       __impureHostDeps = computedImpureHostDeps ++ computedPropagatedImpureHostDeps ++ __propagatedImpureHostDeps ++ __impureHostDeps ++ stdenv.__extraImpureHostDeps ++ [
             |       ^
          450|         "/dev/zero"

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: invalid regular expression '.*.(no_lfs|param||bin)$'
```

**Comment by zbuc** [comment]
Cool, looks good to me. I hit a few macOS-related stumbling blocks but pushed up fixes. I was able to get everything running in the end.

**Comment by conorsch** [comment]
> I hit a few macOS-related stumbling blocks but pushed up fixes.

Nice, thanks for taking a look! Some of the macos-specific entries broke the dev env on Linux for me, so let me tinker a bit more...

**Review by cronokirby — APPROVED** [review]

**Comment by conorsch** [comment]
Nice, thanks both for testing!

**Pull request merged**
