### PR TITLE
Add ADR-001 for Dutch Auctions

### PR DESCRIPTION
**Pull request by cronokirby**
## Describe your changes

This creates a new folder for storing architecture design records, as part of our documentation. This adds the recent Dutch Auction design description here. This should encourage people to write more of them as there's a clear place to put them now.

## Checklist before requesting a review

- [x] If this code contains consensus-breaking changes, I have added the "consensus-breaking" label. Otherwise, I declare my belief that there are not consensus-breaking changes, for the following reason:

  > Just documentation.

### CODE REVIEW

**Comment by conorsch** [comment]
Out of band, we've discussed storing ADRs in a separate repo, or even appending directly to the protocol docs. FWIW, I agree with the very simple approach here: just stick them in their own directory. At any point in the future, we can wrangle the files elsewhere.

**Review by conorsch — APPROVED** [review]
Thanks for taking the time to record this, @cronokirby!

**Review by cratelyn — APPROVED** [review]

**Comment by hdevalence** [comment]
Can we call these PADR or something so they're not confused with cosmos ADRS?

**Comment by cronokirby** [comment]
> Can we call these PADR or something so they're not confused with cosmos ADRS?

Addressed

**Pull request merged**
