### PR TITLE
refactor(wasm): remove wasm crate from monorepo

### PR DESCRIPTION
**Pull request by TalDerei**
References #3819 and https://github.com/penumbra-zone/web/issues/218

### CODE REVIEW

**Comment by TalDerei** [comment]
@grod220 the existing wasm crate is split into `penumbra-wasm` and `penumbra-extension`. The parts of the wasm crate that have logic live in `penumbra-extension`, and wasm-bindgen wrappers are in `penumbra-wasm`. Ideally, the dependency relation should be a one-way relationship where the extension crate in the web can depend on the wasm crate in the monorepo or any other crate, but the wasm crate shouldn't depend on the extension crate. Currently, the `penumbra-wasm` can't live in isolation since this is a **two-way** relationship, where the wasm crate relies on [dependencies](https://github.com/penumbra-zone/penumbra/pull/3772/files#diff-fbc303d3904255ba419fd13b4b971fd968b60333e191dfde3e41b263ab27bcadR1) from the extension crate.

**Comment by TalDerei** [comment]
Additionally, the wasm unit testing suite is currently broken from changes in a previous PR. I'll bisect to isolate the breakage.

**Comment by grod220** [comment]
Ah, `thiserror` (`crates/wasm/src/error.rs`) saved us when we refactored to handle errors and not unwrap everything. I have a feeling we'll want this code to stay with the wasm crate in the core repo and the extension crate will import it.

**Comment by TalDerei** [comment]
The wasm crate has been removed from the penumbra monorepo, and the onus to maintain the wasm stack now explicitly and exclusively falls to the web team. The existing CI workflows and testing infrastructure will be accordingly ported to the web side. 

cc @grod220 @turbocrime @Valentine1898 @Vadim121197 @jessepinho

**Review by grod220 — APPROVED** [review]

**Comment by TalDerei** [comment]
We'll wait to merge this until https://github.com/penumbra-zone/web/pull/478 is in

**Comment by TalDerei** [comment]
@conorsch ready to merge on your green light

**Comment by TalDerei** [comment]
@conorsch ready to merge on your green light

**Comment by conorsch** [comment]
This looks complete to my eye. Will check post-merge that workflows on main still pass, and clean up anything missed. Thanks for your liberal cross-linking, @TalDerei. Really helps to follow the history of discussion around this change, particularly in https://github.com/penumbra-zone/web/issues/218.

**Pull request merged**
