### PR TITLE
renamed ChainParams to ChainParameters

### PR DESCRIPTION
**Pull request by borngraced**
I also simplified `if nullifiers.len() == 0` to `if nullifiers.is_empty()`

fixes: #1227

### CODE REVIEW

**Comment by plaidfinch** [comment]
@borngraced There's a teensy merge conflict in `proto/build.rs`. Could you fix it? Thanks, otherwise this looks good to me!

**Comment by hdevalence** [comment]
@plaidfinch I just rebased it, it should be good to go

**Comment by plaidfinch** [comment]
The smoke test is failing because we merged changes to the JMT which altered its exterior interface, and we're not pinned to a version of the JMT.

**Comment by hdevalence** [comment]
> The smoke test is failing because we merged changes to the JMT which altered its exterior interface, and we're not pinned to a version of the JMT.

Let's roll back the changes to the JMT? We were going to make a plan before actually doing them.

**Pull request merged**
