### PR TITLE
Include`DelegatorVoteView` as an `ActionView` with `Visible` and `Opaque` Variants

### PR DESCRIPTION
**Pull request by ejmg**
## Describe your changes

Small change to `transaction.proto` that moves `DelegatorVoteView` to be included in the section of `ActionView`s that are explicitly documented as having `Opaque` and `Visible` variants. Beyond generated protobuf code from `scripts/protobuf-codegen`, there are no other changes. 

## Checklist before requesting a review

- [x] If this code contains consensus-breaking changes, I have added the "consensus-breaking" label. Otherwise, I declare my belief that there are not consensus-breaking changes, for the following reason:

  > This PR only changes the order of a Protobuf Message definition for the purposes of documentation.

### CODE REVIEW

**Comment by erwanor** [comment]
ACK, the comments are a bit unclear in the proto message, but grouping the `*View` is fine, will merge on green ci (conflict to address first).

**Comment by cratelyn** [comment]
rebased on the latest main, but we'll do that again pending two other forthcoming pr's. (cc: @erwanor)

**Comment by conorsch** [comment]
We intend to release this as part of Testnet 74. It'll need one more rebase after https://github.com/penumbra-zone/penumbra/pull/4368 lands, then should be good to go.

**Review by conorsch — APPROVED** [review]

**Comment by cratelyn** [comment]
thank you for doing this @ejmg! this looks great.

**Pull request merged**
