### PR TITLE
scripts: make docker_compose_freshstart work without DATABASE_URL

### PR DESCRIPTION
**Pull request by hdevalence**

### CODE REVIEW

**Comment by zbuc** [comment]
I think this is ok for local development but it wouldn't work on a production testnet. Probably fine.

**Review by zbuc — APPROVED** [review]

**Comment by hdevalence** [comment]
> I think this is ok for local development but it wouldn't work on a production testnet. Probably fine, the script's purpose is for wiping all state from an existing testnet deployment prior to redeploying anyways, which is more of a local dev process than production process.

Hmm, maybe we should change the script to set the env variable only if it's missing? It seems useful to also use this for setting up all the docker volumes etc. for a production deployment.

**Comment by zbuc** [comment]
That sounds good to me

**Comment by hdevalence** [comment]
Ran into this this morning with @aubrika, so I'm going to merge this now and then we can change it to set only if missing in a later PR.

**Pull request merged**
