### PR TITLE
IBC refactor to remove dependence on `penumbra-shielded-pool`

### PR DESCRIPTION
**Pull request by noot**
At a high level, this wraps the `IbcAction` type with an `IbcActionWithHandler`, which contains an additional generic parameter that implements `AppHandler`. Also updated the `MsgHandler` trait methods to accept additional `AppHandler` generic parameters, so then the IBC messages which implement `MsgHandler` can pass in these parameters when calling `check_stateless`/`try_execute`.

I went with this instead of using global state with an `AppHandler` with a registration mechanism as the `AppHandler` contains generics, and trait objects with generics don't work :/ 

Also moved `Ics20Withdrawal` and the `component::transfer::Ics20Transfer` type into the shielded pool crate.

closes https://github.com/penumbra-zone/penumbra/issues/3127 and also closes https://github.com/penumbra-zone/penumbra/issues/3128.

### CODE REVIEW

**Comment by hdevalence** [comment]
Huh, this seems like a really neat approach. Nice work. I'm not sure I see a downside to doing it this way, the `.with_handler` pattern seems really clean. @avahowell does this seem good?

**Comment by avahowell** [comment]
I like this approach. This PR looks good to me, thanks for taking this on!

**Comment by noot** [comment]
awesome, thanks @hdevalence and @avahowell ! i'll finish up the refactor and then open this up for review :)

**Review by erwanor — APPROVED** [review]
This is really great work, thanks for driving this.

**Pull request merged**
