### PR TITLE
chore: use `anyhow::{bail, Ok, Result}` consistently

### PR DESCRIPTION
**Pull request by kevinji**
There are no functionality changes, and all resulting code should be shorter than before.

### CODE REVIEW

**Comment by erwanor** [comment]
Thanks a lot, this looks great - i'm letting CI run before merging

**Comment by erwanor** [comment]
Sorry, this is unlucky timing - one of our CI workflow broke, a hotfix is in but you will need to rebase against main.

```
git fetch origin && git rebase -i origin/main
```

**Comment by kevinji** [comment]
No worries, just pushed a new commit.

**Comment by conorsch** [comment]
Thanks for this, @kevinji! This is one of those things that makes the code more readable, but often falls by the wayside when making changes. Really appreciate you taking the time.

**Review by erwanor — APPROVED** [review]

**Pull request merged**
