### PR TITLE
view: hack attempting to mitigate split-brain GRPC failures

### PR DESCRIPTION
**Pull request by hdevalence**
This isn't a permanent fix, and it's not the right way to solve the robustness issue (more details TK) but it may help with the immediate problem with `summonerd`, and seems unlikely to add new failure modes.

### CODE REVIEW

**Comment by cronokirby** [comment]
What's with the protobuf lint failures?

**Comment by hdevalence** [comment]
I think it's comparing the state of this branch against `main`, even though the PR is being made against a different branch. Probably the solution is to change the CI workflow to filter to only apply to PRs against `main`.

**Comment by cronokirby** [comment]
Also, are we sure that one second is enough?

**Comment by hdevalence** [comment]
> Also, are we sure that one second is enough?

We are not! But it seems likely, and fits in the middle of the confirmation delay we already put in `pcli`. If it isn't, we'll see it really clearly in the logs, because there will be a warning before an error. So I think it's probably a reasonable starting point.

**Comment by cronokirby** [comment]
> > Also, are we sure that one second is enough?
> 
> We are not! But it seems likely, and fits in the middle of the confirmation delay we already put in `pcli`. If it isn't, we'll see it really clearly in the logs, because there will be a warning before an error. So I think it's probably a reasonable starting point.

Yeah, makes sense, if we still run into this we could do a few retries with exponential backoff, but I'm in favor of merging this as an obviously correct patch for now

**Review by cronokirby — APPROVED** [review]

**Pull request merged**
