### PR TITLE
Augment missing events for governance

### PR DESCRIPTION
**Pull request by cronokirby**
This takes the event related changes from https://github.com/penumbra-zone/penumbra/pull/4708 and pulls them out for independent review and merging.

## Checklist before requesting a review

- [x] If this code contains consensus-breaking changes, I have added the "consensus-breaking" label. Otherwise, I declare my belief that there are not consensus-breaking changes, for the following reason:

  > event emission only.

### CODE REVIEW

**Comment by cronokirby** [comment]
c.f. https://github.com/penumbra-zone/penumbra/pull/4708#discussion_r1677997075 for discussion on the lint failure

**Review by aubrika — APPROVED** [review]
LGTM 👍🏻

**Review by aubrika — CHANGES_REQUESTED** [review]
One hesitation - are we sure renaming the EventEnactProposal proto isn't going to break anything? Seems better not to do this if we can avoid it, although semantically the change does seem like an improvement

**Comment by hdevalence** [comment]
> One hesitation - are we sure renaming the EventEnactProposal proto isn't going to break anything? Seems better not to do this if we can avoid it, although semantically the change does seem like an improvement

Yes, it breaks anything that was using it, which at the time was only the code in that PR

**Pull request merged**
