### PR TITLE
ibc client upgrades

### LINKED ISSUE #635: ibc: implement upgradeclient to allow counterparty chains to upgrade
There are two cases where we need to consider handling upgrades for IBC clients:

- The host chain (penumbra) performs an upgrade.
- A counterparty, a client of which exists on penumbra, performs an upgrade.

First case is tracked in https://github.com/penumbra-zone/penumbra/issues/2985.

This issue refers to the second case. At a high level, in order to handle this case, we must:

- Implement a state handler for `MsgUpgradeClient`, similarly to `MsgUpdateClient`, that allows us to verify that a counterparty included an UpgradeClient in their state which specifies a new ConsensusState and ClientState for that client.
- Once we have verified that the counterparty has committed this data, overwrite the existing client with the newly committed (on the counterparty) ConsensusState and ClientState.

We should replicate existing ecosystem implementations of this functionality, to maintain compatibility. These can be found here:

- [ibc-rs](https://github.com/cosmos/ibc-rs/blob/95704fcede4146fd9039580a8a8ca2218180e400/crates/ibc/src/core/ics02_client/handler/upgrade_client.rs#L16)

ibc-go:
- https://github.com/cosmos/ibc-go/blob/56a519c188ae841818b9ecd11244240941cc5d90/modules/core/02-client/types/msgs.go#L168
- https://github.com/cosmos/ibc-go/blob/56a519c188ae841818b9ecd11244240941cc5d90/modules/core/02-client/keeper/client.go#L111

At a high level,

- Add a new `UpgradeClient` type to the existing IBC action [enum](https://github.com/penumbra-zone/penumbra/blob/a97a0855f2c830c723a678eed7311ff4901b974d/crates/core/component/ibc/src/ibc_action.rs#L21)
- Add new branches to every switch on that enum
- Inside the execution handlers, implement the logic that constructs and verifies the merkle inclusion proofs necessary (see `proof_verification.rs`)
- Once proofs are verified, use the StateWrite trait in client to overwrite the client's consensus and client states

### PR DESCRIPTION
**Pull request by avahowell**
Closes #635

### CODE REVIEW

**Comment by conorsch** [comment]
@avahowell What's the status of this PR? Mergeable for 61 (#3046), or still more work required?

**Comment by hdevalence** [comment]
I think we should delay it until the next cycle.

**Comment by avahowell** [comment]
Yes, this PR only contains the proof verification. we still need to add the message itself and its state machine handling

**Comment by conorsch** [comment]
Merging! This'll ship in 62.

**Pull request merged**
