### PR TITLE
feat: support display seed phrase discreetly

### PR DESCRIPTION
**Pull request by Halimao**
Running `pcli init soft-kms generate` will print a seed phrase in the terminal, this is dangerous.

This pr added a new option `--display-discreetly` to support displaying seed phrases discreetly on an alternate screen.

image

image

### CODE REVIEW

**Comment by Halimao** [comment]
@erwanor @hdevalence GM sir, could you please help me to review this pr😀

**Comment by Halimao** [comment]
@erwanor Hi sir, could you please help me to review this pr😀

**Comment by erwanor** [comment]
Hey @Halimao, sorry this took so long but I am going to review this in the next couple days, possibly amending the branch before merging this in. Thanks for taking a stab at this!

**Comment by Halimao** [comment]
> Hey @Halimao, sorry this took so long but I am going to review this in the next couple days, possibly amending the branch before merging this in. Thanks for taking a stab at this!

Hi sir, could u please help me review this PR then?

**Comment by erwanor** [comment]
Thanks for your patience with this, I didn't want this to sit any longer so I workshopped the PR myself to expedite it, making the alt screen the default option so that it doesn't show in buffered backscrolls. Let's merge this!!

**Review by erwanor — APPROVED** [review]

**Pull request merged**
