### PR TITLE
staking: emit event when tombstoning active/jailed/inactive vals

### PR DESCRIPTION
**Pull request by erwanor**
## Describe your changes

This PR adds a `EventTombstoneValidator` message that is emitted on the *first* validated evidence message for validators that are `Active | Inactive | Jailed`.

The evidence event is defined as follow:

```proto
message EventTombstoneValidator {
  // The height at which the offense occurred.
  uint64 evidence_height = 1;
  // The height at which the evidence was processed.
  uint64 current_height = 2;
  // The validator identity key.
  keys.v1.IdentityKey identity_key = 4;
  // The validator's Comet address.
  bytes address = 5;
  // The voting power for the validator.
  uint64 voting_power = 6;
}
```

My first instinct was to reach for storing the evidence in nonverifiable storage, hoping it would make it easier for node runners to query it. But I later realized, that comet only gives us a filtered version that does not include the actual double signed headers, or offending signatures.

## Checklist before requesting a review

- [x] If this code contains consensus-breaking changes, I have added the "consensus-breaking" label. Otherwise, I declare my belief that there are not consensus-breaking changes, for the following reason:

  > Event emission

### CODE REVIEW

**Comment by erwanor** [comment]
We'll need to port and complete the event coverage for the staking component as part of #3504 and #3797

**Comment by conorsch** [comment]
This looks great, @erwanor, and provides us with a nice shape for adding the other state transitions, as described in https://github.com/penumbra-zone/penumbra/issues/3746#issuecomment-2049976212. The only thing I'm unclear on is why the emission is gated on transitions out of `Active | Inactive | Jailed`. The state machine diagram makes it clear that Defined and Disabled validators can also be Tombstoned—why not also emit the event in those scenarios?

**Comment by erwanor** [comment]
Good point, my reasoning is that those transitions are less relevant because they don't affect the consensus view at all. Something else that I had in mind is that generating valid equivocation evidence rounds down to "free", hence why we only record the first offense, and tie it to 1/ a validator definition upload 2/ having reached the minimum stake threshold 3/ being enabled.

**Review by conorsch — APPROVED** [review]

**Comment by conorsch** [comment]
Thanks, that's clearly explained!

**Comment by erwanor** [comment]
There's a good overview in the spec: https://protocol.penumbra.zone/main/concepts/validators.html, happy to chat about it offline as well!

**Review by cratelyn — APPROVED** [review]

**Pull request merged**
