### PR TITLE
spec: threshold: fix some rendering bugs and make notation more consistent

### PR DESCRIPTION
**Pull request by avahowell**
this PR fixes some rendering bugs in the rendered LaTex, changes the notation a bit to be more consistent, and adds a note on the encryption SNARK note to the threshold spec

### CODE REVIEW

**Comment by aubrika** [comment]
I'm getting a `ParseError: KaTeX parse error: Can't use function '$' in math mode at position 49: …2} + v_3 2^{48}$̲$ with $v_i \in…` on trying to preview the markdown - looks like an error on line ~63?

**Comment by avahowell** [comment]
huh, is that when running `mdbook serve`?

**Comment by aubrika** [comment]
> huh, is that when running `mdbook serve`?

`mdbook serve` doesn't seem to(?) throw an error there, I saw the above when viewing as preview in VSCode using the  markdownlint extension

**Comment by avahowell** [comment]
optimistically merging to fix the rendering issues on protocol.penumbra.zone

**Pull request merged**
