### PR TITLE
linear liquidity strategies in pcli

### LINKED ISSUE #4112: dex_utils: implement v3 approximations
**Is your feature request related to a problem? Please describe.**
Currently, our implementation of replicated market makers only support approximating the `x*y=k` curve over an "infinite" liquidity range. As pointed by @hdevalence, this means that the position distribution is skewed at the extremes of this range:

```
 ID                                                                State     Fee        Sell Price             Reserves
 plpid1t0yx3cn2fp72s7gy09ra4zrvx7nacc2ftpp85d5m7aqhffglv03suncr9a  opened  42bps        10penumbra         740.967746gn
 plpid1xt2vdazq9j4wpmpe29cj2rc2768k0hta9a32sk0j0h640l2c4gmsnswvp8  opened  42bps         5penumbra         243.814939gn
 plpid1a5z05wwsvrc4hu9v4azw76d6m84837lvtvrtulgv6czlxpraxjmqkr9lwz  opened  42bps  3.333334penumbra         189.311849gn
(snip)
 plpid1vn7jydp9cx9vf7kuk7qcc7ff7qv3v4ftj3v3eujdn8rmytffuqas0ce9ca  opened  42bps        2.800001gn    21.351881penumbra
 plpid15jn60qg5s590kzu25qr7nxpe8ujkyg5h0mlsee94aa6ev205pv9sw2sxj0  opened  42bps        2.900001gn    20.256501penumbra
 plpid1m5e8xchzl49td9s356ggge2e7e2vv3v4k7kywzssz2jtnc0ekktsnv5hj3  opened  42bps               3gn  1164.486839penumbra
 ```

It would be more capital efficient and just plain better to add a UniV3 concentrated liquidity replication that takes a price, an inventory, and a range, and builds the replicated portfolio corresponding to that curve.

### PR DESCRIPTION
**Pull request by hdevalence**
Closes #4112 

## Describe your changes

Description TK

Screenshot 2024-08-10 at 5 01 56 PM

This strategy is the line labeled "demo", and it's simpler to implement than UniV3 but with a similarly shaped PVF

## Checklist before requesting a review

- [ ] If this code contains consensus-breaking changes, I have added the "consensus-breaking" label. Otherwise, I declare my belief that there are not consensus-breaking changes, for the following reason:

  > REPLACE THIS TEXT WITH RATIONALE (CAN BE BRIEF)

### CODE REVIEW

**Comment by hdevalence** [comment]
There are rendering issues when using this with USDC, because there's no entry in the asset registry, so it shows a rounded price for upenumbra in terms of uusdc:
```
You want to provide liquidity on the pair upenumbra:transfer/channel-2/uusdc
You will need:
 -> 121945740upenumbra
 -> 31250000transfer/channel-2/uusdc
You will create the following positions:
 ID                                                                State     Fee                      Sell Price                         Reserves
 plpid1j9mdlj040jd32swz32c3ycc95ayu5ff9t36scng0mp3y04zxdpgq05fflq  opened  50bps                      4upenumbra  6250000transfer/channel-2/uusdc
 plpid194g8zhvpf9qkehz0yszqm425swvcgtgc2jyapewcytk4cxc2szrqqeun5y  opened  50bps                      4upenumbra  6250000transfer/channel-2/uusdc
 plpid1lxmtpwv9rpgwkfam6tvetke7pg2pzwhgpq4hr3yf76lpffak26xqa4nt2z  opened  50bps                      4upenumbra  6250000transfer/channel-2/uusdc
 plpid1mq7p9d8yadlgdk4dl5cwsv7pmx4e5xmufuvt0h3gthjm85mzwreqz3kr2j  opened  50bps                      3upenumbra  6250000transfer/channel-2/uusdc
 plpid17dwusw4qc6xf26xfy940hxda0usxcxvrrqaglhrke7r6efvfdksq5334wn  opened  50bps                      3upenumbra  6250000transfer/channel-2/uusdc
 plpid1kp84g54yq3m24nqwrv7vz9g2u96z679mrl4ght3c76c7y4ch4v3sf8uezp  opened  50bps  416666transfer/channel-2/uusdc                       15penumbra
 plpid1hkny675ladn7uf3z2jza9vh8lwu5z7eceehyyvs2dlzvy2gl0kpsy77lpj  opened  50bps  450001transfer/channel-2/uusdc                13.888888penumbra
 plpid16n0f9wduwmtc6g95hpsyd9s4a7cs2x30f0k5ryntc6le09760cuqcw4tne  opened  50bps  483334transfer/channel-2/uusdc                12.931034penumbra
 plpid1zzrywrtjv73xh0ssrf5j3yya2alnr4myzanljec7dgklj8pvpqdq6pt59v  opened  50bps  516667transfer/channel-2/uusdc                12.096774penumbra
 plpid1cx9kg6sjsgqzjj2age6hk3gypyau082y62rkms5s2v6tdf4phz0qv86f6z  opened  50bps  550001transfer/channel-2/uusdc                11.363636penumbra
 plpid1vlm45q8a0zjadns3d5zddl684yykfv7h7lxcqwqvy3uspdrvs4csl6s62z  opened  50bps  583334transfer/channel-2/uusdc                10.714285penumbra
 plpid1jgwsegzklgpe9vkht2lmwwzw8h275l6xd56vmdflawyqujtnur0q89t7hd  opened  50bps  616667transfer/channel-2/uusdc                10.135135penumbra
 plpid1lh73fch4x9tqvw9x2ztq0lwnrmxdq6ajldnjs4uz75298vvuekps658dt0  opened  50bps  650001transfer/channel-2/uusdc                 9.615384penumbra
 plpid1nuqx0mcdwjptzaky7eamsqd0hr4cfh23nwzd4ahws9lwazf68zlqd4n9xw  opened  50bps  683334transfer/channel-2/uusdc                 9.146341penumbra
 plpid1e3tpqprrqgra9z0s36xvy68mcxv2rlfyt9dw2xl5v437hxc5f3rsj0lvf0  opened  50bps  716667transfer/channel-2/uusdc                  8.72093penumbra
 plpid16ykmlz4yur94slvd7sx77cs6v5arpscrrjd4vdf0p92dy7srq3aqlvkzcm  opened  50bps  750001transfer/channel-2/uusdc                 8.333333penumbra
 ```
 This should be fixed by allowing pcli to load a registry from its home directory rather than rearranging the rendering code

**Comment by hdevalence** [comment]
Rebased on top of #4801

**Review by cronokirby — APPROVED** [review]
LGTM, tested the different options with an actual registry. There are some rough edges we can sand off in subsequent PRs related to parsing using the asset registry, to avoid needing to know internal asset identification as thoroughly.

**Comment by conorsch** [comment]
> There are some rough edges we can sand off in subsequent PRs related to parsing using the asset registry

Tracked in #4803.

**Pull request merged**
