### PR TITLE
Fix about 20 typo

### PR DESCRIPTION
**Pull request by miles-six**
I have been studying this repository for a long time, and whenever I come across a typo, I fix it. 

I discovered 20 typos in a total of 19 files. Then I merged them together.

The code quality is exceptionally high, so sincerely hope my PR can help make this repository more standardized.

### CODE REVIEW

**Review by cratelyn — APPROVED** [review]
this is very kind of you, @miles-six! thank you very much, this looks good to me. :heavy_check_mark:

**Comment by miles-six** [comment]
Thank you! Waiting for you merge it.

**Comment by miles-six** [comment]
I'm not very familiar with GitHub commands, so I made some modifications based on your previous commit not cherry-pick.
However, things seem to have gotten worse. Do I need to submit a new PR? Sorry about that.

**Comment by miles-six** [comment]
ok,i will try do it again with run run ./deployments/scripts/protobuf-codegen locally after fix them

**Comment by cratelyn** [comment]
> @cratelyn Hey,I want to know that only satisfy the ci checks can be merged?

yes, pr's need to satisfy all ci checks to be merged.

**Pull request closed without merging**
