### PR TITLE
chore: update chain id for rhea 63

### PR DESCRIPTION
**Pull request by conorsch**
Does not include updated discord allocations, see
for more info #3147. Refs #3182.

### CODE REVIEW

**Comment by conorsch** [comment]
The [CI failure on the smoke test](https://github.com/penumbra-zone/penumbra/actions/runs/6644887877/job/18055010026?pr=3227) doesn't make sense to me: the allocations are unchanged between 62 & 63, so there shouldn't be a failure. I suspect the custom GHA caching setup may be interfering.

**Comment by conorsch** [comment]
> there shouldn't be a failure.

Indeed, the smoke test passes for me locally on this branch.

**Comment by conorsch** [comment]
I've asked @zbuc to take a look here. It may be worthwhile to disable/revert the buildjet caching logic on the smoke test workflow in a separate PR, and see if that unblocks things here once rebased.

**Comment by zbuc** [comment]
> The [CI failure on the smoke test](https://github.com/penumbra-zone/penumbra/actions/runs/6644887877/job/18055010026?pr=3227) doesn't make sense to me: the allocations are unchanged between 62 & 63, so there shouldn't be a failure. I suspect the custom GHA caching setup may be interfering.

I'm actually seeing some changes to the allocations:

```
eclipse~/repos/penumbra[chain-id-for-rhea|✚1…15⚑45] % diff testnets/063-rhea/allocations.csv testnets/062-iapetus/allocations.csv 
71,79c71,79
< "1_000_000_000_000","upenumbra","penumbrav2t1u3w40vzl9qhcptd4t7jqs285dqqx3dj6nqc3hmlvplsmpt30v83hxt29mes2g8wwnzhvaf0r9rywsv20nvzpz0rj0x0vr3mz0wf0xnpppr00tn9wm58ehrdyhjgc68vays8kt5"
< "2_000_000_000_000","gm","penumbrav2t1u3w40vzl9qhcptd4t7jqs285dqqx3dj6nqc3hmlvplsmpt30v83hxt29mes2g8wwnzhvaf0r9rywsv20nvzpz0rj0x0vr3mz0wf0xnpppr00tn9wm58ehrdyhjgc68vays8kt5"
< "2_000_000_000_000","test_atom","penumbrav2t1u3w40vzl9qhcptd4t7jqs285dqqx3dj6nqc3hmlvplsmpt30v83hxt29mes2g8wwnzhvaf0r9rywsv20nvzpz0rj0x0vr3mz0wf0xnpppr00tn9wm58ehrdyhjgc68vays8kt5"
< "10_000_000_000_000","test_btc","penumbrav2t1u3w40vzl9qhcptd4t7jqs285dqqx3dj6nqc3hmlvplsmpt30v83hxt29mes2g8wwnzhvaf0r9rywsv20nvzpz0rj0x0vr3mz0wf0xnpppr00tn9wm58ehrdyhjgc68vays8kt5"
< "2_000_000_000_000","test_eth","penumbrav2t1u3w40vzl9qhcptd4t7jqs285dqqx3dj6nqc3hmlvplsmpt30v83hxt29mes2g8wwnzhvaf0r9rywsv20nvzpz0rj0x0vr3mz0wf0xnpppr00tn9wm58ehrdyhjgc68vays8kt5"
< "2_000_000_000_000","gn","penumbrav2t1u3w40vzl9qhcptd4t7jqs285dqqx3dj6nqc3hmlvplsmpt30v83hxt29mes2g8wwnzhvaf0r9rywsv20nvzpz0rj0x0vr3mz0wf0xnpppr00tn9wm58ehrdyhjgc68vays8kt5"
< "10_000_000_000_000","test_usd","penumbrav2t1u3w40vzl9qhcptd4t7jqs285dqqx3dj6nqc3hmlvplsmpt30v83hxt29mes2g8wwnzhvaf0r9rywsv20nvzpz0rj0x0vr3mz0wf0xnpppr00tn9wm58ehrdyhjgc68vays8kt5"
< "10_000","pizza","penumbrav2t1u3w40vzl9qhcptd4t7jqs285dqqx3dj6nqc3hmlvplsmpt30v83hxt29mes2g8wwnzhvaf0r9rywsv20nvzpz0rj0x0vr3mz0wf0xnpppr00tn9wm58ehrdyhjgc68vays8kt5"
< "1_000_000","cube","penumbrav2t1u3w40vzl9qhcptd4t7jqs285dqqx3dj6nqc3hmlvplsmpt30v83hxt29mes2g8wwnzhvaf0r9rywsv20nvzpz0rj0x0vr3mz0wf0xnpppr00tn9wm58ehrdyhjgc68vays8kt5"
---
> "1_000_000_000_000","upenumbra","penumbrav2t1fwtqq3fuluel20dfga4stvlqyqpq8m7j9etzy5we6af6rgmhslfevgalva8vgzvdm586w20l53sunckhzns050w9jgmxnme46guxku340ym0hn8t6pt9perlzghfz0dee8n8z9"
> "2_000_000_000_000","gm","penumbrav2t1fwtqq3fuluel20dfga4stvlqyqpq8m7j9etzy5we6af6rgmhslfevgalva8vgzvdm586w20l53sunckhzns050w9jgmxnme46guxku340ym0hn8t6pt9perlzghfz0dee8n8z9"
> "2_000_000_000_000","test_atom","penumbrav2t1fwtqq3fuluel20dfga4stvlqyqpq8m7j9etzy5we6af6rgmhslfevgalva8vgzvdm586w20l53sunckhzns050w9jgmxnme46guxku340ym0hn8t6pt9perlzghfz0dee8n8z9"
> "10_000_000_000_000","test_btc","penumbrav2t1fwtqq3fuluel20dfga4stvlqyqpq8m7j9etzy5we6af6rgmhslfevgalva8vgzvdm586w20l53sunckhzns050w9jgmxnme46guxku340ym0hn8t6pt9perlzghfz0dee8n8z9"
> "2_000_000_000_000","test_eth","penumbrav2t1fwtqq3fuluel20dfga4stvlqyqpq8m7j9etzy5we6af6rgmhslfevgalva8vgzvdm586w20l53sunckhzns050w9jgmxnme46guxku340ym0hn8t6pt9perlzghfz0dee8n8z9"
> "2_000_000_000_000","gn","penumbrav2t1fwtqq3fuluel20dfga4stvlqyqpq8m7j9etzy5we6af6rgmhslfevgalva8vgzvdm586w20l53sunckhzns050w9jgmxnme46guxku340ym0hn8t6pt9perlzghfz0dee8n8z9"
> "10_000_000_000_000","test_usd","penumbrav2t1fwtqq3fuluel20dfga4stvlqyqpq8m7j9etzy5we6af6rgmhslfevgalva8vgzvdm586w20l53sunckhzns050w9jgmxnme46guxku340ym0hn8t6pt9perlzghfz0dee8n8z9"
> "10_000","pizza","penumbrav2t1fwtqq3fuluel20dfga4stvlqyqpq8m7j9etzy5we6af6rgmhslfevgalva8vgzvdm586w20l53sunckhzns050w9jgmxnme46guxku340ym0hn8t6pt9perlzghfz0dee8n8z9"
> "1_000_000","cube","penumbrav2t1fwtqq3fuluel20dfga4stvlqyqpq8m7j9etzy5we6af6rgmhslfevgalva8vgzvdm586w20l53sunckhzns050w9jgmxnme46guxku340ym0hn8t6pt9perlzghfz0dee8n8z9"
1338,1339c1338,1339
< "1_000__000_000","upenumbra","penumbrav2t13vh0fkf3qkqjacpm59g23ufea9n5us45e4p5h6hty8vg73r2t8g5l3kynad87u0n9eragf3hhkgkhqe5vhngq2cw493k48c9qg9ms4epllcmndd6ly4v4dw2jcnxaxzjqnlvnw"
< "1_000","test_usd","penumbrav2t13vh0fkf3qkqjacpm59g23ufea9n5us45e4p5h6hty8vg73r2t8g5l3kynad87u0n9eragf3hhkgkhqe5vhngq2cw493k48c9qg9ms4epllcmndd6ly4v4dw2jcnxaxzjqnlvnw"
---
> "1_000__000_000","upenumbra","penumbrav2t147mfall0zr6am5r45qkwht7xqqrdsp50czde7empv7yq2nk3z8yyfh9k9520ddgswkmzar22vhz9dwtuem7uxw0qytfpv7lk3q9dp8ccaw2fn5c838rfackazmgf3ahhvhypxd"
> "1_000","test_usd","penumbrav2t147mfall0zr6am5r45qkwht7xqqrdsp50czde7empv7yq2nk3z8yyfh9k9520ddgswkmzar22vhz9dwtuem7uxw0qytfpv7lk3q9dp8ccaw2fn5c838rfackazmgf3ahhvhypxd"
6312,6313c6312,6313
< "1_000__000_000","upenumbra","penumbrav2t1gl609fq6xzjcqn3hz3crysw2s0nkt330lyhaq403ztmrm3yygsgdklt9uxfs0gedwp6sypp5k5ln9t62lvs9t0a990q832wnxak8r939g5u6uz5aessd8saxvv7ewlz4hhqnws"
< "1_000","test_usd","penumbrav2t1gl609fq6xzjcqn3hz3crysw2s0nkt330lyhaq403ztmrm3yygsgdklt9uxfs0gedwp6sypp5k5ln9t62lvs9t0a990q832wnxak8r939g5u6uz5aessd8saxvv7ewlz4hhqnws"
---
> "1_000__000_000","upenumbra","penumbrav2t1vmmz304hjlkjq6xv4al5dqumvgk3ek82rneagj07vdqkudjvl6y7zxzr5k6qq24yc7yyyekpu9qm7ef3acg2u8p950hs6hu3e73guq5pfmmvm63qudfx4qmg8h7fdweydr93ku"
> "1_000","test_usd","penumbrav2t1vmmz304hjlkjq6xv4al5dqumvgk3ek82rneagj07vdqkudjvl6y7zxzr5k6qq24yc7yyyekpu9qm7ef3acg2u8p950hs6hu3e73guq5pfmmvm63qudfx4qmg8h7fdweydr93ku"
```

**Comment by zbuc** [comment]
@conorsch the smoke test passes after reverting the changes to allocations

**Pull request merged**
